spring:
  application:
    name: demo
#  datasource:
#    url: jdbc:h2:mem:membersdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#  h2:
#    console:
#      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/deltaspacedb
    username: postgres
    password: ${POSTGRES-PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB


aws:
  s3:
    bucket-name: reddit-clone-deltaspace
    region: us-east-1
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
