spring:
  application:
    name: demo
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

groq:
  api:
    key: ${GROQ_API_KEY:default_or_dummy_key}
    model: openai/gpt-oss-120b

nasa:
  api:
    key: ${NASA_API_KEY:DEMO_KEY}

aws:
  s3:
    bucket-name: reddit-clone-deltaspace-eu
    region: eu-central-1
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.hibernate: OFF
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.tool.hbm2ddl: OFF
management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: "reddit-backend"
    distribution:
        percentiles-histogram:
           "http.server.requests": true

