spring:
  application:
    name: demo
  datasource:
    #url: jdbc:postgresql://localhost:5432/deltaspacedb3
    url: jdbc:postgresql://172.31.46.238:5432/deltaspacedb #toggle this before ./build.ps1
    username: ${POSTGRES_EC2_USERNAME}
    #password: ${POSTGRES_PASSWORD}
    password: ${POSTGRES_EC2_PASSWORD} # toggle this before ./build.ps1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

groq:
  api:
    key: ${GROQ_API_KEY}

aws:
  s3:
    bucket-name: reddit-clone-deltaspace-eu
    region: eu-central-1
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
